from django.contrib import admin
from django.utils.safestring import mark_safe

from workshop.models import JewelryType, Material, Gem, Jewelry, Client, Order, OrderItem


class JewelryTypeAdmin(admin.ModelAdmin):
    list_display = ("name", "get_html_photo")
    list_display_links = ("name",)
    search_fields = ("name",)
    prepopulated_fields = {"slug": ("name",)}
    fields = ("name", "slug", "photo")

    def render_change_form(self, request, context, *args, **kwargs):
        context["adminform"].form.fields["slug"].widget.attrs["placeholder"] = "Autogenerated from the 'Name' field"
        return super().render_change_form(request, context, *args, **kwargs)

    def get_html_photo(self, object):
        if object.photo:
            return mark_safe(f"<img src='{object.photo.url}' height=100 style=\"display: flex; margin: 0 auto\"")

    get_html_photo.short_description = "Image"


class JewelryAdmin(admin.ModelAdmin):
    list_display = ("name", "type", "weight", "price", "get_html_photo")
    list_display_links = ("name",)
    search_fields = ("name", "type__name", "materials__name", "gems__name")
    prepopulated_fields = {"slug": ("name",)}
    fields = ("name", "slug", "description", "weight", "price", "type", "materials", "gems", "photo", "created_at", "updated_at")
    readonly_fields = ("created_at", "updated_at")

    def render_change_form(self, request, context, *args, **kwargs):
        context["adminform"].form.fields["slug"].widget.attrs["placeholder"] = "Autogenerated from the 'Name' field"
        return super().render_change_form(request, context, *args, **kwargs)

    def get_html_photo(self, object):
        if object.photo:
            return mark_safe(f"<img src='{object.photo.url}' height=100 style=\"display: flex; margin: 0 auto\"")

    get_html_photo.short_description = "Image"


class OrderItemInlineAdmin(admin.TabularInline):
    model = OrderItem


class OrderAdmin(admin.ModelAdmin):
    fields = ("client", "created_at", "updated_at")
    readonly_fields = ("created_at", "updated_at")
    search_fields = ("client__name", "client__email", "client__phone_number")
    inlines = (OrderItemInlineAdmin,)


class ClientAdmin(admin.ModelAdmin):
    fields = ("name", "email", "phone_number", "created_at", "updated_at")
    readonly_fields = ("created_at", "updated_at")
    search_fields = ("name", "email", "phone_number")


admin.site.register(Jewelry, JewelryAdmin)
admin.site.register(Order, OrderAdmin)
admin.site.register(Client, ClientAdmin)
admin.site.register(JewelryType, JewelryTypeAdmin)
admin.site.register(Material)
admin.site.register(Gem)
