# Generated by Django 4.1.6 on 2023-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_jewelry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewelrytype',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='jewelrytype',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
