# Generated by Django 4.1.6 on 2023-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_jewelry_slug_jewelrytype_photo_jewelrytype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='jewelrytype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
