# Generated by Django 4.1.6 on 2023-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_jewelry_slug_alter_jewelrytype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
