# Generated by Django 4.1.6 on 2023-02-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_jewelry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='jewelry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='gems',
            field=models.ManyToManyField(blank=True, to='workshop.gem'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('jewelry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.jewelry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.order')),
            ],
        ),
    ]
